### ISSUE TITLE
Plugin marked as signed but failed to start

### ISSUE THREAD

**Issue by Rickman** [alexanderzobnin/grafana-zabbix#1042]
**Describe the bug**
I have installed and enabled the Zabbix plugin, it's appears as signed. After resrarting Grafana, when i go to the add data source option within Grafana, Zabbix does not appear in the list.

**Expected behavior**
I expect the Zabbix data source to appear in the list of available data sources

**Screenshots**
![Capture](https://user-images.githubusercontent.com/1157647/92005599-93fe6e80-ed3b-11ea-8a18-6d8fb985dc3c.jpg)

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5    | 5.0.1  | 4.0.1

**Comment by xJMV** [comment]
In grafana.conf add "alexanderzobnin-zabbix-datasource" to "allow_loading_unsigned_plugins" and restart Zabbix-Server.

Ex: `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

Refresh your browser and see if it is fixed.

**Comment by Rickman** [comment]
I'm afraid that doesn't work. 

I did try that with version 4.0 as well and had the same issue, it just refuses to show up as a source.

**Comment by xJMV** [comment]
Check your logs. You will notice what part of the plugin is not loading. In my case the **-datasource** part was not loading. So adding the exception as stated above fixed the problem.

**Comment by Rickman** [comment]
Hi,

I tried this, it doesn't appear to work.

![Capture](https://user-images.githubusercontent.com/1157647/92011595-353cf300-ed43-11ea-90eb-edd70d1adb8a.PNG)

The logs do suggest that it's not loading due to being unsigned though.

![Capture2](https://user-images.githubusercontent.com/1157647/92011736-6a494580-ed43-11ea-855c-6c6eec6e23a5.PNG)

Am i missing something here?

**Comment by Rickman** [comment]
OK, that was me being stupid, got it working, thanks for the help!

**Comment by alexanderzobnin** [comment]
Looks like datasource is still treated as unsigned by grafana-server. So `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource` is still required to run plugin.

**Comment by ruchimal** [comment]
I have already set the value to allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource but it is giving the above error.

![image](https://user-images.githubusercontent.com/8912847/92116559-9b904700-ee11-11ea-8df1-9e67db6cf7c6.png)

**Comment by Rickman** [comment]
> 
> 
> I have already set the value to allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource but it is giving the above error.
> 
> ![image](https://user-images.githubusercontent.com/8912847/92116559-9b904700-ee11-11ea-8df1-9e67db6cf7c6.png)

You need to remove the `;` at the start of the line in the config file.

So the line should be exactly:

`allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

That got it working for me.

**Comment by ruchimal** [comment]
Please below screen dump from my ini file

![image](https://user-images.githubusercontent.com/8912847/92122635-54a64f80-ee19-11ea-9bcc-080a3cd4e305.png)

**Comment by Rickman** [comment]
Did you restart Grafana and refresh the browser?

**Comment by ruchimal** [comment]
I did everything and did the installation couple of times (including different laptops) but it is still the same. Please note i am running Grafana in windows 10 environments.

**Comment by alexanderzobnin** [comment]
@ruchimal That might be an issue with Windows env. Do you see something specific in the logs?

**Comment by ruchimal** [comment]
@Alexander Please find the attached log file for your reference.
[grafana.log](https://github.com/alexanderzobnin/grafana-zabbix/files/5169523/grafana.log)

**Comment by alexanderzobnin** [comment]
Created an issue in grafana repo: grafana/grafana#27364

**Comment by WUZHIQIANGX** [comment]
thanks, get it!

**Comment by rburkhall** [comment]
> I have already set the value to allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource but it is giving the above error.
> 
> ![image](https://user-images.githubusercontent.com/8912847/92116559-9b904700-ee11-11ea-8df1-9e67db6cf7c6.png)

Ensure that you placed the item under [plugins], I made the same mistake adding it to the end of the file.

**Comment by ruchimal** [comment]
> Created an issue in grafana repo: [grafana/grafana#27364](https://github.com/grafana/grafana/issues/27364)

Hello Alexander, This problem is still persisting in version 7.2.0-beta1 even though the grafana team has closed the 7.2 milestones. Please note that i have used WindowsOS for this testing.

**_"t=2020-09-22T10:24:45+0530 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins\\alexanderzobnin-zabbix-app\\datasource-zabbix"
t=2020-09-22T10:24:45+0530 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-09-22T10:24:45+0530 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-09-22T10:24:45+0530 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned]"
t=2020-09-22T10:24:45+0530 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-09-22T10:25:19+0530 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=127.0.0.1 time_ms=0 size=29 referer=
t=2020-09-22T10:25:28+0530 lvl=info msg="Successful Login" logger=http.server User=admin@localhost"_**

![GrafanaError](https://user-images.githubusercontent.com/8912847/93845537-d245d880-fcbe-11ea-8249-5631545d3116.PNG)

**Comment by alexanderzobnin** [comment]
Closing since it was fixed in Grafana.

**Comment by gabriiellduarte** [comment]
Olá, estou tendo o mesmo problema porém estou com o no Windows rodando a versão mais recente do grafana 9.3.1
recebo esse erro 
![image](https://user-images.githubusercontent.com/11770579/206498810-cce7fb16-3d7e-4913-9515-6a3bb09fc285.png)
