### ISSUE TITLE
Dashboard not found on https://grafana.com/grafana/dashboards 

### ISSUE THREAD

**Issue by xenexis** [alexanderzobnin/grafana-zabbix#1115]
Hi Alexander,

Seems like the dashboard has been removed from https://grafana.com/grafana/dashboards , there is nothing in a datasource option, also nothing on a search by name ....
Is there any other way to get the dashboard ? 

Thanks!

**Comment by alexanderzobnin** [comment]
Hi!
Looks like data source type is missing in the dropdown filter. But filtering by name works fine. You can open this issue in the Grafana repo since it's not a plugin bug.

![Screenshot from 2020-12-22 15-46-33](https://user-images.githubusercontent.com/4932851/102890118-f73c1a00-446c-11eb-9185-427694c55823.png)
