### ISSUE TITLE
Support item tags instead of application in Zabbix 5.4

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#1258]
Since item tags is a [replacement](https://www.zabbix.com/documentation/current/manual/introduction/whatsnew540#item_tags_have_replaced_applications) for the applications, plugin should support a new way for filtering Items.

**Comment by mpopovi** [comment]
Hello, I am still on version 5.0.13 and plan to stay on it due to our support contract. I see in the API that Tag Filtering is available, however using your newest Grafana Plugin, I dont see that option. The version that I am on supports Application and Tags as well.

![image](https://user-images.githubusercontent.com/2784404/130286092-15ad7f2f-31e6-47e8-9438-8ed950af332e.png)

![image (2)](https://user-images.githubusercontent.com/2784404/130286651-7cfe97b1-c291-4c6a-b81a-9372cb58b005.png)
![image (3)](https://user-images.githubusercontent.com/2784404/130286704-59949539-6281-48d8-936e-08c72b06c444.png)
![image (4)](https://user-images.githubusercontent.com/2784404/130286961-c18e9d17-252a-4ea1-a0e7-746b3d43f73b.png)
