### ISSUE TITLE
Build for FreeBSD

### ISSUE THREAD

**Issue by hellmany** [alexanderzobnin/grafana-zabbix#1301]
**Is your feature request related to a problem? Please describe.**
Could you please add freebsd_amd64 compiled plugin to the package and sign it?

**Describe the solution you'd like**
I compiled it with 
`go mod vendor
env GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -mod=vendor -o ./dist/zabbix-plugin_freebsd_amd64 ./pkg`
but i've got signature invalid/modified error

Thanks.

**Comment by overhacked** [comment]
I'd also like if you could begin building with GOOS=freebsd again, also. I'm able to build the backend binary with no problem and load the plugin with `allow_loading_unsigned_plugins = "alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-triggers-panel,alexanderzobnin-zabbix-app"`.

Is there a CI or testing issue that I can help with so that the signed plugin can support FreeBSD again?

**Comment by alexanderzobnin** [comment]
Hi! I can add FreeBSD build to the release. How do you install plugins since we don't have official Grafana build for freebsd, manually? I can add it as a separate package in the github release.

**Comment by hellmany** [comment]
from ports =)

**Comment by overhacked** [comment]
Yep, there is a maintained FreeBSD port for Grafana, and the plugin-cli works perfectly to install alexanderzobnin-zabbix-app but it won't run due to the lack of FreeBSD backend binary.

**Comment by alexanderzobnin** [comment]
Ok, got it. Thus, I need to add this to the package.

**Comment by Henry78** [comment]
Related: https://github.com/alexanderzobnin/grafana-zabbix/issues/1022

**Comment by hellmany** [comment]
Please, release signed plugin for freebsd, it's a pain to install it.

**Comment by hellmany** [comment]
Now i cannot load plugin in Grafana 8
"Failed to validate plugin signature. Will skip loading"

allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app,alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-app,alexanderzobnin-zabbix-triggers-panel

Cannot help

**Comment by paulofragoso** [comment]
I can not compile anymore in FreeBSD. How can I install your plugin using this OS?

Granfana 9 and Zabbix 6 are installed in FreeBSD without problems.

Thanks,
Paulo.

**Comment by paulofragoso** [comment]
After corrects my dependencies I could compile onde plugin for FreeBSD for Zabbix6.

Thanks,
Paulo.

**Comment by overhacked** [comment]
Hi, I don't mean to be a bother, just a friendly reminder: I internally maintain a FreeBSD port of this plugin for our infrastructure, which I can't make public because of the unsigned plugin issue. Apart from that, the backend compiles with **zero modifications** when setting `GOOS=freebsd`.

There are a couple of open, duplicate issues requesting FreeBSD support: #1402, #1237, and #1203. I'll go ahead and open a PR that would close this issue, with fingers crossed. Thank you!
