### ISSUE TITLE
json: cannot unmarshal number 1633004437.459 into Go struct field TimeSeriesData.series.TS of type int64

### ISSUE THREAD

**Issue by drajv-y** [alexanderzobnin/grafana-zabbix#1320]
**Describe the bug**
&from=1633004132575&to=1633006364306 - doesn't work
&from=now-2d&to=now - works
&from=now-2d&to=now-1d - work

**Expected behavior**
the ability to select graphs with the mouse

**Screenshots**
![изображение](https://user-images.githubusercontent.com/71210138/135477463-b5209a36-1829-4b84-8533-7cb16244f8bc.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.5   | 5.4.4  | 4.2.4                 |

**Comment by renatoborges78** [comment]
I came across this same problem I had to downgrade the version to solve it, I went back to Grafana 7.5.10 and plugin 4.1.5.
All other versions are showing this issue you cited or acknowledging the screen disappears.

**Comment by baugarcia** [comment]
Just wanted to thank you for sharing the solution. Was having the exact same issue and after downgrading both grafana and the zabbix plugin to the versions you specified, everything worked like a charm!

**Comment by nbriche** [comment]
Same issue as well:
Grafana 8.2.2 (6232fe07c0)
Plugin 4.2.4
Zabbix 5.4.6

**Comment by nbriche** [comment]
I think it happens with direct DB connection: when disabling that feature, I can select a random time range with no error.

It may be due to [mysql.ts:6](https://github.com/alexanderzobnin/grafana-zabbix/blob/f8a843244debc0e4bf2c16844b6152d60f010988/src/datasource-zabbix/zabbix/connectors/sql/mysql.ts#L6), where a division of a clock value (in seconds) results in a rounding error and a float value for a timestamp, which can't be cast as an int64 by whatever comes next.

If I modify the corresponding code in production (plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js) with a search for "historyQuery:function", then changing var o="clock", I can again select a random range with no error (after a ctrl+F5 to force the browser to fetch the modified file, of course).

Depending on what exactly that division/multiplication was supposed to do, however, the resulting graph may or may not be exactly accurate but I didn't see any obvious error.

**Comment by Ghotome** [comment]
Same issue occurred after updating:

Grafana CLI version 8.2.3
 alexanderzobnin-zabbix-app version: 4.2.4
zabbix_server (Zabbix) 5.4.6

Propose from @nbriche didn't work for me :(

**Comment by nbriche** [comment]
I will revisit it and check whether my solution was a fluke, or I'll give more precise instructions of how I managed it.

Note that since the plugin is signed, any modification to its files will disable it when the Grafana server restarts and you'll have to reinstall the plugin (ask me how I know)

**Comment by Ghotome** [comment]
Okay, thank you!

Another question - is there hope for update which resolve this problem in future?

**Comment by szodan** [comment]
> I think it happens with direct DB connection: when disabling that feature, I can select a random time range with no error.

That works for me. Thanks.

**Comment by weiserhei** [comment]
> 
> then changing var o="clock"

I have replaced `var o="clock DIV "+a+" * "+a;` with your code and the error is gone. Everything _seems_ to be working fine again, however I cant tell if that is introducing some other bugs. 

My dashboards arent too fancy, but Im certain removing `DIV a * a` has some effects somewhere and is no final fix 😄 

Grafana 8.2.3

**Comment by nbriche** [comment]
So I've restarted Grafana and had to reinstall the Zabbix plugin; the bug is present. I will retrace my previous steps for @Ghotome (and anyone else) to ensure I didn't mess up somewhere.

The module.js file I've mentioned is a one-liner minified, at `/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js` (Ubuntu 20.04). Its size is (currently, v4.2.4) 141425 bytes, SHA256 hash is `5a6b2d6ba40eb76685535ad16556bc236e9edd73de687827094f4dbd59b9c900`.

The specific variable I'm modifying is defined at position 73012: `var o="clock DIV "+a+" * "+a;`

My steps:

1. I currently have a tab open with a bugged dashboard. I force a no-cache reload (ctrl+F5) just to be sure: yes, still bugged.
2. I replace that code with `var o="clock";`
3. I force a no-cache reload (ctrl+F5): The dashboard loads correctly, no bug.
4. I restore the module.js file with its previous, unmodified version. I force a no-cache reload: the dashboard is bugged.

I won't for now correct the variable again, since it will break the plugin when the server restarts. I will just disable DirectDB Connection for now.

**Comment by Ghotome** [comment]
Okay, thank you, it is helped to resolve time range problem, but we faced another after that. Maybe you can help again :)
Here screenshot: 
![IMG_20211112_164413_178.jpg](https://user-images.githubusercontent.com/31542463/141485521-38a53cbc-7b99-4fa4-9c09-5a2e7c4402cc.jpg)

This problem both on time series graph and old graph.

**Comment by nbriche** [comment]
I don't know what it's supposed to look like though...
It _looks_ like the data points don't connect? I think I've faced that problem; I think I resolved that either by using "Connect null values" to Always, or (I guess the "proper" way?) by using a groupBy(1m, avg) function to my queries.

**Comment by Ghotome** [comment]
Sorry for delay, @nbriche.

I've tried your suggestion, here what I've accomplish:
1. Setting "Connect null values" to "Always" didn't give any result. 
2. To every query set I added a groupBy function with args 1m, avg, that didn't work too. 
3. Both this solutions on same graph didn't work too.
4. Changing value '1m' in groupBy function didn't give any result, same as changing second value. 

Here some screenshots:

1. That what we have now:
![image](https://user-images.githubusercontent.com/31542463/141778053-7998d12d-1e41-47e5-985a-686e4db97755.png)

2. And setting, set as you suggested:
![image](https://user-images.githubusercontent.com/31542463/141778247-898b0e42-4531-4b45-a4c7-e121c14bfbed.png)

**Comment by nbriche** [comment]
Does it also happen with Direct DB Connection disabled? If so (and maybe even if not) this problem may not be related to this current issue. Someone with more experience with Grafana than I (I only started Grafana two weeks ago, I'm not all that familiar yet) may have an idea if you open a specific issue about this.

**Comment by Ghotome** [comment]
This problem occurred just after we disable Direct DB future.
The steps above we've done with Direct DB Connection future disabled.

**Comment by nbriche** [comment]
In that case this is probably not related to this issue. You should check if there's already an issue open for it (or maybe already resolved!), and if not, open one.

**Comment by szodan** [comment]
> > I think it happens with direct DB connection: when disabling that feature, I can select a random time range with no error.
> 
> That works for me. Thanks.      (it turned out that in the API the data does not always read and load on the chart: szodan)

Hi, I I had the same problem, originally the plugin connected directly to the mysql database but there was a problem with the time range, the query contained the timestamp with milliseconds after the dot, I changed the timezone from current to UTC and the timestamp no longer contained the time with millisecond accuracy. The data is finally showing up, I'm just testing this and it seems to be working as expected. I gave up on the API, it's faster on direct

**Comment by alexanderzobnin** [comment]
@nbriche yes, you're right it's a division bug. Disabling direct db connection is a workaround.

**Comment by B3DTech** [comment]
I have Direct DB connection disabled in the datasource configuration and I still have the issue.

When running a test with Direct DB disabled, I still appear to get a Direct DB connection though:
Zabbix API version: 4.4.10, DB connector type: MySQL
