### ISSUE TITLE
Grafana does not get units from Zabbix in 4.2

### ISSUE THREAD

**Issue by meyerder** [alexanderzobnin/grafana-zabbix#1321]
Issue:  Incorrect Results Returned with 4.2 Branch plugin

Grafana  v8.1.5 (c725a4259a)
Zabbix  API version: 5.0.13

Screenshots below show.. Nothing really complex... The strange thing is it only appears to be different on the Memory and Drive Space that I have found so far...  Initially noticed it with the Stats Display so I tried Table just to make sure I was not missing anything... Seems to be incorrect data no matter how I look at it..

Note:  I tried the 4.2 and 4.2.4 Branch (same results)

![Plugin_Install](https://user-images.githubusercontent.com/28714840/135537231-761e333a-1f08-4203-9a0c-46c91a8141eb.GIF)
![4_1_plugin](https://user-images.githubusercontent.com/28714840/135537285-26fadb09-f9b4-4d0d-8d59-d28f014e44fb.GIF)
![4_2](https://user-images.githubusercontent.com/28714840/135537295-dbbe028b-abc4-433a-b050-54cd935b62b7.GIF)
![Zabbix_Screen](https://user-images.githubusercontent.com/28714840/135537303-ae0a134c-00e1-42a3-8f3f-ab4afc324d52.GIF)

**Comment by meyerder** [comment]
This is interesting...  I noticed after I posted it one version said "GiB" and one Said "GB"  Both 4.2 and 4.1 Branches when No Units are applied say 16976740352.0 

Ok Im very confused...  

Version 4.1.5 The unit is Bytes(SI)  and it shows correct (which is what I had it)
![4_1_5_units](https://user-images.githubusercontent.com/28714840/135540063-1744e00c-b31d-4b23-bc7b-e0b322ab275e.GIF)

Version 4.2.x  If I change it to ICE it then is proper with the right labels... Bear in mind the version of Grafana is Not Changing..

![4_2_Units](https://user-images.githubusercontent.com/28714840/135540164-a7e9d4a7-b25d-4b2a-9ad6-7e45943d7d6d.GIF)

**Comment by alexanderzobnin** [comment]
Ok. Since version 4.2 plugin makes metric queries completely on the backend. There's no feature that uses units from Zabbix on the backend, so I think what happend is:
1. Panel is configured to use GB (bytes SI).
2. Zabbix returns GiB (bytes IEC in Grafana), but in Zabbix it shown as a GB (which is not 100% accurate, actually).
3. In 4.1 plugin overrides units configured in the panel and returns GiB.
4. In 4.2 it returns no units configured and Grafana uses units from panel (GB).

So you just need to set proper units which is bytes IEC.
I should add this feature to the backend, but there's some issues with it. It should be possible to override this unit in the panel config.

**Comment by CirnoT** [comment]
>It should be possible to override this unit in the panel config.

It seems that you can not do that with Grafana v8. For example I've tried to display graph of W calculated from % usage from UPS data but version 4.2.5 insists that my data modified with `scale` is in % and no amount of play would convince it otherwise. To make matters worse, any value above 100 is treated as 100% making usage of `scale` useless on % units.
