### ISSUE TITLE
Data alignment/stacking issues

### ISSUE THREAD

**Issue by borjasueiro** [alexanderzobnin/grafana-zabbix#1334]
From the issue [#1211](https://github.com/alexanderzobnin/grafana-zabbix/issues/1211), the bug still remains at 4.2.4 version. When I try to stack values with different update intervals it does not work correctly.
Screenshot of the issue:
![image](https://user-images.githubusercontent.com/49273030/136410224-621b57c6-f4b0-443b-a8ff-fef67d67c4c4.png)

Screenshot of expected behavior:
![image](https://user-images.githubusercontent.com/49273030/136410316-a08ae538-007e-4b7f-9816-0e5efb510557.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.2.0   | 5.0.10 | 4.2.4                |

**Comment by CompPhy** [comment]
Should probably also mention... This is only happening on Time Series panels.  If you use the Graph (old) panel then it still works the old way and you don't run into these interval issues.

**Comment by alexanderzobnin** [comment]
@borjasueiro do you use flexible intervals? Could you provide info about using items (update intervals)?

**Comment by CompPhy** [comment]
We do not use flexible intervals.  However, we do have a lot of data points that use trappers for various application level data.  Since these come from external scripts, and can sometimes take more than a few seconds to run, the timestamps don't always line up exactly when displaying multiple things on one panel.

When looking at something like "Last Hour" we would see the interval auto calculating as low as 2 seconds.  Since some of those timestamps can have more than 2 seconds of variance, this cases it to display strangely.  As soon as we forced the minimum interval to 1 minute, which is our minimum data gathering interval, then these display problems went away.  I don't necessarily blame the Zabbix plugin for the display issue here, as this is how the new time interval calculations are supposed to work.  It can give more granular display if you have data to fill in those gaps.

I'm just saying, it appears that there is support for setting a global option on the data source.  However, it would appear this plugin has not implemented this option as of yet, and we are forced to modify individual panels any time this display issue happens.

**Comment by alexanderzobnin** [comment]
@borjasueiro do you have data alignment enabled?

@CompPhy could you post a screenshots of your case?

**Comment by CompPhy** [comment]
Here's a quick example.  In this case you can see exactly what I mean.  It's calculating the minimum interval to be 2s, so it has to fill in the missing values with zeros.  Then if I just force the minimum interval to 1 minute, those bogus zeros go away.  We also have some that look like the original submitter, but I think it's less clear to see what's happening there.

![Screenshot 2021-11-01 122035](https://user-images.githubusercontent.com/10223024/139706694-07a8e1aa-8e98-46b4-9dc9-879c8221b5f8.png)

![Screenshot 2021-11-01 122056](https://user-images.githubusercontent.com/10223024/139706707-a7592142-598d-4b84-bf3e-d06a02a888ae.png)

**Comment by borjasueiro** [comment]
@alexanderzobnin nor do I use flexible intervals. But if I use several items I will probably collect the value in different intervals. Almost all of them have 1 minute or 2 minutes update interval.
I have tested both, with data alignment and without the option enabled.

**Comment by mjtrangoni** [comment]
In my case with a 1 minute interval frequency, I get the right representation for 4 hours and it is broken for 5 hours timeframe.

4 hours:
![image](https://user-images.githubusercontent.com/261502/141289134-bc101754-72ef-4e95-8340-da300c524ea0.png)

5 hours:
![image](https://user-images.githubusercontent.com/261502/141289289-90a53a8f-c0b0-43d3-a808-e36bdaf3efcf.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.2.2   | 5.0.11  | 4.2.4                 |

**Comment by alexanderzobnin** [comment]
I thought about the solution for a long time, but it looks like there's no good one. I can fix stacking for the graphs obtained from the one query, but for the multiple it's tricky since it do not share the same context. So the best way to fix it is a workaround suggested by @CompPhy https://github.com/alexanderzobnin/grafana-zabbix/issues/1334#issuecomment-956388394

Interval should be set to the maximum item update interval you have. For example, if you have an item with 1 minute interval and another one with 10 minutes, then set it to `10m`. @borjasueiro please, let me know if it works for you.

**Comment by CompPhy** [comment]
What about my suggestion of exposing a global minimum on the plugin?  Most of our graphs work fine just setting 1m as the minimum, but it's pretty frustrating when you have to remember to set it on every single panel.  Grafana documentation seems to suggest that there is a "global" value that can be used, but the plugin needs to implement.

**Comment by alexanderzobnin** [comment]
This is quite tricky to handle multiple query and apply any data processing that can help to avoid stacking issue. I added this for the single query, it works pretty well in most cases, but this is not possible for case like this one, where multiple queries are using. So there're some workarounds:
1. Use min interval in query options and set it according to the longest item collection interval.
2. Use single query if it's possible.

I'm closing this because I don't see any good solution for this issue and there're workarounds that can help to avoid it.

**Comment by alexanderzobnin** [comment]
@CompPhy that's a good point. I will take a look.
