### ISSUE TITLE
No data since Grafana updated to 8.3.5

### ISSUE THREAD

**Issue by EHRETic** [alexanderzobnin/grafana-zabbix#1388]
**Describe the bug**
No data in any dashboard and the message "origin not allowed" popping up since my Grafana instance updated from 8.3.4 to 8.3.5 overnight:

![image](https://user-images.githubusercontent.com/28634810/153191219-0c94ad05-6e09-4aed-a5d3-94dd533fa2ae.png)

The "origin not allowed" warning will also come in plugin configuration when pressing "Save & test".

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.5   | 5.4.10  | 4.2.4                 |

**Comment by Vizzyy** [comment]
same thing is happening to me. I'm using an apache reverse proxy

**Comment by koraktor** [comment]
Similar for me since 8.3.5, and 8.3.6 has the same problem.
I‘m unable to login with the same error message.

<img width="434" alt="image" src="https://user-images.githubusercontent.com/66112/153346960-e8ee29d5-c9b4-4b87-86ee-5ebd142cd925.png">

Setup is running in Docker with a nginx reverse proxy.
Bypassing the proxy or downgrading to 8.3.4 solves the problem.

**Comment by onlime** [comment]
Same here after having upgraded 8.3.4 to 8.3.6 on Debian Bullseye / Apache 2.4 `ProxyPass / http://localhost:3000/`. The following in `grafana.ini` did not help either:

```ini
[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app
```

Had to revert to Grafana 8.3.4 to fix it.

**Comment by crafty-ua** [comment]
https://github.com/grafana/grafana/issues/45117#issuecomment-1033842787

^ That might help

**Comment by eithor** [comment]
I can confirm that setting "ProxyPreserveHost On" for Apache2 removes/workaround the issue.

**Comment by EHRETic** [comment]
> [grafana/grafana#45117 (comment)](https://github.com/grafana/grafana/issues/45117#issuecomment-1033842787)
> 
> ^ That might help

Hi, that solved the issue, thanks a lot!
But I'm lacking some nginx knowledge to understand it fully. 

This is my updated nginx configuration (which is kind of my default for most of my webapps servers):
 ```
       location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
```
Googling doesn't really help me to understand the differences/complementarity of X-Forwarded-Host  & Host lines. 
If somebody can give a complement of info, I'll be very happy! 😉

**Comment by DasSkelett** [comment]
> Googling doesn't really help me to understand the differences/complementarity of X-Forwarded-Host & Host lines.
> If somebody can give a complement of info, I'll be very happy! 😉

The `Host` header is required and present in every single HTTP(S) request. It tells the webserver or reverse proxy along the way for which server/domain you asking exactly.

It is set to the value of the hostname and port part of the requested URL. If you open `https://example.com/help` in your browser, it'll be `example.com`.

Now, nginx and Apache change the value of the `Host` header by default for proxied requests. So if you ask for `https://example.com/help`, and the rev proxy proxies it to `http://localhost:3000/`, then the final host header of the request that reaches the backend (Grafana here) will be `localhost:3000`.

This helps e.g. if the connection to your backend is TLS encrypted (so the domain matches the certificate and the proxy can validate successfully), or goes through another proxy that expects your "internal" hostname. Usually this is fine, and to help your backend figure out some things, like building URLs for links on the website or logging, you can add an `X-Forwarded-Host` header which tells the backend what the original `Host` header was (`example.com`) .

However in the case of Grafana 8.3.5+ (and some other applications), they explicitly do checks on the host header, in Grafana's case to compare it to the `Origin` header for cross-site request forgery checks. This means that the `Host` header needs to stay like it was originally, and can't be changed by the reverse proxy, as otherwise the CSRF check will always trigger. The check can't be done on the `X-Forwarded-Host` header, because that one is not protected (by the browser) like the `Host` header, and can be manipulated through Javascript.

**Comment by EHRETic** [comment]
> However in the case of Grafana 8.3.5+ (and some other applications), they explicitly do checks on the host header, in Grafana's case to compare it to the `Origin` header for cross-site request forgery checks. This means that the `Host` header needs to stay like it was originally, and can't be changed by the reverse proxy, as otherwise the CSRF check will always trigger. The check can't be done on the `X-Forwarded-Host` header, because that one is not protected (by the browser) like the `Host` header, and can be manipulated through Javascript.

So if I understand it correctly, for single DNS entries/services like this one, the corrected configuration should be my standard for the future? 😊

**Comment by EHRETic** [comment]
> For most other applications it won't make a difference either way, so you could see your current configuration as new standard, yeah.

It is now my new standard, thanks again for those precious details! 😉
