### ISSUE TITLE
Alias as Item Name on all queries

### ISSUE THREAD

**Issue by cdaher78** [alexanderzobnin/grafana-zabbix#1399]
**Describe the bug**
Alias from Stats, Gauge, Time Series and every plugin brings "Host":"Item" names

**Expected behavior**
Only show "Item" name as on v7.5

**Screenshots**

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.4.1   | 5.0.20 |            4.2.5     |

I'd like to have all my queries (stats, gauge, time series graphics, etc) to show aliases with "Item" name.
I have several dashboards with lot of querries and I can't just use a setalias($__zbx_item_name) for each one. It will take so much time.
Is there such a script or a fix to make this version compatible in this regard?

Thanks in advance.

**Comment by cdaher78** [comment]
The best regex I found to set the correct alias name is ``` (?<=:.)[\s\S]* ```

So I'd like a tip to how could I set this regex on every dashboard / panels I have.

Thanks

**Comment by alexanderzobnin** [comment]
Hi! In latest Grafana versions there's a labels string in a metric name. So since plugin includes host as a label, maybe it makes sense to remove default host prefix.

**Comment by alexanderzobnin** [comment]
I think it's the same reason as #1444. So fixed and will be available in the next release.

**Comment by cdaher78** [comment]
Great news and great job!

**Comment by rrz** [comment]
Hi!
I updated grafana 7.3.6 to grafana 8.5.13 and zbx plugin 4.2.10
but now every zabbix item has _host_ prefix
before
![image](https://user-images.githubusercontent.com/424308/191675858-d7daef1e-1c5d-4cb9-8e5e-06887b5dea48.png)

now
![image](https://user-images.githubusercontent.com/424308/191676047-42ae8944-e119-46db-b708-f615724be113.png)

and that breaks many overrides, transforms and etc. And I have more than 1000 dashboards
Issue seems to me still actual, and if not, can you please tell what to do to get expected behavior without manually puting setAlias($__zbx_item) on every zbx panel?

Thanks!
