### ISSUE TITLE
[grafana-3.0] Broken upgrade path from 2.6: Empty queries in panels

### ISSUE THREAD

**Issue by 2ion** [alexanderzobnin/grafana-zabbix#150]
I just test-drove fbebb1f.

We have a complex Zabbix dashboard. After upgrading Grafana 2.6 to today's nightly build of 3.0 and the Zabbix plugin to the grafana-3.0 branch, all panels in the dashboard were defunct: The contents of all panels' queries appeared empty (all text inputs were empty: Host group, Host, Application, Item, even alias). Manually re-entering all queries worked perfectly fine and yielded functional panels.

On the other hand, the datasource continued to work without changing anything.

(Forgot to add) No errors in the Grafana log.

Is this an issue with the plugin, or a Grafana bug?

**Comment by alexanderzobnin** [comment]
@2ion There are some broken changes in queries structure in new plugin verison. I think about some migration tool because it's a problem for people with many dashboards.

**Comment by leleobhz** [comment]
```
||/ Name                 Version         Architecture    Description
+++-====================-===============-===============-=============================================
ii  grafana              3.0.0-pre1      amd64           Grafana
```

With this version, Datasource even get recognized. Changing plugin.json to the following results in Datasrouce getting recognized but this message appears and no data can be queued or add'ed: "Plugin Error Failed to find exported plugin component for ds-config-zabbix"

```
{
  "pluginType": "datasource",
  "name": "Zabbix",
  "id": "zabbix",

  "type": "datasource",
  "serviceName": "ZabbixAPIDatasource",

  "module": "app/plugins/datasource/zabbix/datasource",

  "partials": {
    "config": "app/plugins/datasource/zabbix/partials/config.html"
  },

  "metrics": true,
  "annotations": true
}
```

**Comment by alexanderzobnin** [comment]
@leleobhz I need to check it. Grafana 3.0 still in development and sometimes plugin api may be changed.

**Comment by alexanderzobnin** [comment]
@leleobhz indeed, plugin api was changed. Need some time to get stable api and then I'll fix it.

**Comment by elarrexo** [comment]
hello, I have zabbix server 3.0.3 and grafana 3.1, after installing and configuring in grafana the datasource, creating the graphics on the board not refects nothing while the board triggers if it does and is updated in the grafana.log file shows the following when creating the consuta for graphic .
  **lvl = info msg = "Request Completed" logger = context userId = 1 OrgID = 1 uname = admin method = GET path = / public / app / plugins / app / alexanderzobnin-zabbix-app / module.js remote_addr status = 404 = 192.168 .100.115 time_ns = 0 size = 19**
Additionally I have noticed that if I create a new host in zabbix also updated in grafana, but still does not show anything on the charts.
Thank you for your comments

**Comment by elarrexo** [comment]
Apologies for using someone else's ticket, was the one most like what happens to me with the plugin grafana-zabbix

**Comment by alexanderzobnin** [comment]
@elarrexo may be something like #232 or #231 ?

**Comment by elarrexo** [comment]
hello, I suggest cases
  windows use my platform is the next centos centos 7 zabbix and 7 grafana, attached screenshots my grafana.
![captura de pantalla de 2016-07-18 11 22 24](https://cloud.githubusercontent.com/assets/8645032/16922249/796c6d66-4cda-11e6-85ea-3ac2e8ee2c65.png)
![captura de pantalla de 2016-07-18 11 22 55](https://cloud.githubusercontent.com/assets/8645032/16922369/dad179ca-4cda-11e6-8939-383c54925eaf.png)
![captura de pantalla de 2016-07-18 11 27 51](https://cloud.githubusercontent.com/assets/8645032/16922377/e01d4238-4cda-11e6-932d-dee199011bdd.png)

**Comment by alexanderzobnin** [comment]
@elarrexo Do you mean that you have changed OS to Centos 7 and now all works fine? Do you mean server-side of client-side (browser's platform)?

**Comment by elarrexo** [comment]
Thanks for your prompt response.
My installation is linux from the start, yet I have the problem screenshots displays the graphic without information, I could say where I find a log file or some more indications that I may be the problem.
The display of the web is from a client, as my linux server has no graphical environment is a minimal installation

**Comment by alexanderzobnin** [comment]
I just want to clarify a reason of the problem.

**Comment by elarrexo** [comment]
hello , I was reviewing the ruling to indicate when you run the developer tools and go to the following meeting console tab, perhaps you can help me do that graphics are displayed.
------------------------------------------------------------------------------
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:9:1986
Expected color but found '#fbf069\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. grafana.dark.min.82697b13.css:9:3369
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:9:3733
Expected color but found '#\30 39\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. grafana.dark.min.82697b13.css:9:5168
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:9:5859
Expected color but found '#\30 39\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. grafana.dark.min.82697b13.css:9:7434
Unknown property 'user-select'.  Declaration dropped. grafana.dark.min.82697b13.css:18:3383
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:18:3828
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:18:4124
Error in parsing value for 'background'.  Declaration dropped. grafana.dark.min.82697b13.css:18:4238
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:18:4351
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:18:4466
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:18:4581
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:18:4696
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:18:4811
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:18:4926
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:18:12595
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:18:12699
Expected end of value but found '0.75'.  Error in parsing value for 'margin'.  Declaration dropped. grafana.dark.min.82697b13.css:18:13223
Expected color but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. grafana.dark.min.82697b13.css:18:13315
Unknown property 'touch-action'.  Declaration dropped. grafana.dark.min.82697b13.css:18:13498
Expected color but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. grafana.dark.min.82697b13.css:18:13635
Error in parsing value for 'margin-bottom'.  Declaration dropped. grafana.dark.min.82697b13.css:18:13842
Error in parsing value for 'margin-bottom'.  Declaration dropped. grafana.dark.min.82697b13.css:18:14635
Error in parsing value for 'margin-left'.  Declaration dropped. grafana.dark.min.82697b13.css:18:15569
Expected end of value but found '1.5'.  Error in parsing value for 'margin'.  Declaration dropped. grafana.dark.min.82697b13.css:18:16044
Error in parsing value for 'font-size'.  Declaration dropped. grafana.dark.min.82697b13.css:18:17074
Expected color but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. grafana.dark.min.82697b13.css:18:17670
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:18:17793
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:18:17867
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:21:1501
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:21:1664
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:21:1830
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:21:2001
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. grafana.dark.min.82697b13.css:21:2171
Unknown property 'speak'.  Declaration dropped. grafana.dark.min.82697b13.css:21:22274
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. grafana.dark.min.82697b13.css:21:22408
Error in parsing value for 'font-size'.  Declaration dropped. grafana.dark.min.82697b13.css:21:24923
Expected end of value but found '1.5'.  Error in parsing value for 'margin'.  Declaration dropped. grafana.dark.min.82697b13.css:21:25115
Error in parsing value for 'margin-bottom'.  Declaration dropped. grafana.dark.min.82697b13.css:21:25262
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:33402
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:33423
Expected color but found 'solid'.  Expected end of value but found 'solid'.  Error in parsing value for 'border-right'.  Declaration dropped. grafana.dark.min.82697b13.css:21:34933
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:35066
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:35087
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:35518
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:35539
Expected color but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. grafana.dark.min.82697b13.css:21:37671
Error in parsing value for 'margin-bottom'.  Declaration dropped. grafana.dark.min.82697b13.css:21:48407
Unknown property 'user-select'.  Declaration dropped. grafana.dark.min.82697b13.css:21:49464
Expected end of selector or a user action pseudo-class after pseudo-element but found '.'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:49861
Expected end of selector or a user action pseudo-class after pseudo-element but found '.'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:50654
Expected end of selector or a user action pseudo-class after pseudo-element but found '.'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:51216
Error in parsing value for 'top'.  Declaration dropped. grafana.dark.min.82697b13.css:21:53367
Unknown property 'pointer'.  Declaration dropped. grafana.dark.min.82697b13.css:21:54324
Error in parsing value for 'width'.  Declaration dropped. grafana.dark.min.82697b13.css:21:54502
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:68903
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:68924
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:72675
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:72696
Unknown pseudo-class or pseudo-element '-ms-expand'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:73956
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:74156
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:74272
Unknown pseudo-class or pseudo-element 'placeholder'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:74331
Unknown property 'appearance'.  Declaration dropped. grafana.dark.min.82697b13.css:21:75022
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. grafana.dark.min.82697b13.css:21:85299
Unknown pseudo-class or pseudo-element '-webkit-scrollbar'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88029
Unknown pseudo-class or pseudo-element '-webkit-scrollbar'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88070
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88107
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88204
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88265
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88326
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88385
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88511
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88588
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88665
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-button'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88740
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-track-piece'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88815
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:88876
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. grafana.dark.min.82697b13.css:21:89100
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:91595
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:91616
Error in parsing value for 'pointer-events'.  Declaration dropped. grafana.dark.min.82697b13.css:21:96436
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:111826
Error in parsing value for 'display'.  Declaration dropped. grafana.dark.min.82697b13.css:21:111847
Error in parsing value for 'background-color'.  Declaration dropped. new-dashboard
----------------------------------------------------------------------------------------
![zabbix2](https://cloud.githubusercontent.com/assets/8645032/17263496/0f3046ea-55a7-11e6-8c16-8d11535db7b3.JPG)
![zabbix1](https://cloud.githubusercontent.com/assets/8645032/17263497/0f4c941c-55a7-11e6-9dc3-daeee54e8bbf.JPG)

**Comment by elarrexo** [comment]
![zabbix3](https://cloud.githubusercontent.com/assets/8645032/17263633/a4ddd3ba-55a7-11e6-8f0a-c8d08c540e13.JPG)

**Comment by alexanderzobnin** [comment]
@elarrexo Can you enable `JS` tab in Console?

**Comment by elarrexo** [comment]
hello aelxander attached screenshot
![zabbix4](https://cloud.githubusercontent.com/assets/8645032/17298917/a74476fa-57d1-11e6-8e89-c738005a1181.JPG)

**Comment by alexanderzobnin** [comment]
@elarrexo  Can you also inspect `Network` tab for Zabbix API responses?

**Comment by elarrexo** [comment]
![zabbix6](https://cloud.githubusercontent.com/assets/8645032/17299385/bf550078-57d3-11e6-9aeb-c1b8ab2e0667.JPG)
![zabbix5](https://cloud.githubusercontent.com/assets/8645032/17299386/bfc52880-57d3-11e6-8183-62367502ef39.JPG)

**Comment by elarrexo** [comment]
Alexander, in the event it easier for you to review the problem you live associate the url .
Thank you very much for your help and collaboration
 this is my url http://186.5.66.67:3000 of my grafana test  the default user and password

**Comment by alexanderzobnin** [comment]
Hm... Seems mistake in zabbix url:
```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
```
Try to check server name.

**Comment by alexanderzobnin** [comment]
Sorry, it's due `direct` mode.

**Comment by alexanderzobnin** [comment]
Really strange, but plugin works. Zabbix api just returns empty history. Do you see graphs in zabbix?

**Comment by elarrexo** [comment]
i attached my zabbix graph cpu load

![zabbix7](https://cloud.githubusercontent.com/assets/8645032/17308580/6436b57e-5800-11e6-9321-7cf39f484752.JPG)

**Comment by elarrexo** [comment]
hello Alexander, today I changed the parameter I point and graphics but from 4 am stopped. I can check that ??

![zabbix8](https://cloud.githubusercontent.com/assets/8645032/17335801/f63ee45a-58a0-11e6-9cb1-4e261f03c3df.JPG)

**Comment by alexanderzobnin** [comment]
May be some troubles with timezones?

**Comment by elarrexo** [comment]
Alexander thank you very much , corrected time zone and started to run
