### ISSUE TITLE
Zabbix datasource configuration "with CA Cert"

### ISSUE THREAD

**Issue by kapilyanamandra** [alexanderzobnin/grafana-zabbix#1552]
Hi All,

I recently enabled https for Zabbix and I updated my datasource in Grafana to use HTTPS url. I also had to enable “CA Cert” and upload the cert used for zabbix under “TLS/SSL Auth Details” for the datasource test to pass. Screenshot below.

![image](https://user-images.githubusercontent.com/13930366/211913415-f007df37-3e13-43ec-8bdc-e6f1bc2a8589.png)

I wanted to know which config file (may be grafana.ini) holds this updated info and what are the lines in the config file 

1. to enable "with CA Cert"
2. Upload/configure the CA cert under "TLS/SSL Auth details" as showed in above screenshot.

Once I know the config file and the lines that need to be added or updated, I can incorporate that into my Grafana install build pipeline.

Please help.

Thank you.

Kapil

**Comment by alecxvs** [comment]
The configuration file that would reflect this change involves datasource provisioning, because this setting is datasource-specific: https://grafana.com/docs/grafana/latest/administration/provisioning/

However, if you want to configure the CA Cert for the whole instance, you should install it on your system (outside of Grafana). The paths where Go (which Grafana and the zabbix plugin backend uses) looks for CA Certs are listed here: https://stackoverflow.com/a/40051432

**If you choose this path** you should follow your distribution specific documentation for installing CA Certs, since there may be more steps than just "copy crt file into directory". Some distros require that you run additional commands to "install" the cert.
