### ISSUE TITLE
You don't have permission to access /zabbix/api_jsonrpc.php/

### ISSUE THREAD

**Issue by fanshouxing** [alexanderzobnin/grafana-zabbix#162]
403 Forbidden

Forbidden
You don't have permission to access /zabbix/api_jsonrpc.php/
on this server.

Thank you!

**Comment by alexanderzobnin** [comment]
Check your web-server config. Also try to change data source mode from proxy to direct - sometimes grafana backend add trailing `/` to the request.

**Comment by fanshouxing** [comment]
thank you.    But I use a direct access mode error, using the proxy pattern is ok

Unknown error
Cannot read property 'url' of undefined

**Comment by tjbonzo** [comment]
I was able to fix my problem by setting my noproxy environment variable - apparently zabbix-cli has problems if it goes through a proxy. Or
unset HTTP_PROXY
unset http_proxy

**Comment by victorbcredidio** [comment]
> I was able to fix my problem by setting my noproxy environment variable - apparently zabbix-cli has problems if it goes through a proxy. Or
> unset HTTP_PROXY
> unset http_proxy

Hey @tjbonzo 

I'm having the same problem, and even though it says it's "not permited" I checked all permissions and it still the same.
I also tried to access using default zabbix/grafana configurations, and nothing changes.

Can you explain with a little bit more of detail how you solved this issue?
I mean, are these variables set on Linux env, or are they accessable only with zabbix-cli?

**Comment by victorbcredidio** [comment]
Hi fellas!

After some time analyzing this issue I discovered what is causing it.

My apache web server had the "Evasive Module" and "Secure Module" active. Based on this post "https://www.reddit.com/r/zabbix/comments/9ysur0/trouble_with_grafana_zabbix_api_plugin/" I disabled both, and the issue was gone. 

I went a little further, and disabled only one of them in different times. 
I came to the conclusion that the "Evasive Module" is the issue. Since it's meant to deal with DoS, I only suspect that it was blocking the multiple requests on grafana. It's odd, since it's a "all-in-one server" (both zabbix and grafana are on my test machine), so this module of apache is blocking the server itself. 

I disabled the modules only by moving them from /etc/httpd/conf.d/ to my home directory. Since the httpd.conf file (apache's configuration file) is including everything on /etc/httpd/conf.d/, that's all I needed to do.
