### ISSUE TITLE
Need to be able to suppress triggers in maintenance mode

### ISSUE THREAD

**Issue by intrepidsilence** [alexanderzobnin/grafana-zabbix#186]
For the Triggers panel we need the ability to filter out items in maintenance mode.

**Comment by mdiorio** [comment]
Shouldn't be setting your triggers to ignore while in maintenance mode, or setting your maintenance mode to not collection data so triggers don't fire?

**Comment by intrepidsilence** [comment]
Not necessarily.  Just because we put something in maintenance mode which prevents us from generating tickets it does not mean that we don't want a record of any triggers that fired during the period.  Just like the Dashboard in Zabbix we should be able to filter items in maintenance here as well.

**Comment by mdiorio** [comment]
Touche.  New to Zabbix but loving it.  So much better than Nagios, and Grafana-Zabbix pushed it over the top for me.    I'm just getting systems added, so set my first maintenance window yesterday.  I can see this being a feature improvement for Zabbix too.  Record the trigger, but differently if in a maintenance window - maybe as an INFO severity, or a custom Severity instead of Warning or Critical.

**Comment by intrepidsilence** [comment]
Zabbix already tracks whether a trigger fired during a maintenance window.

**Comment by volter** [comment]
No, it doesn't.

**Comment by intrepidsilence** [comment]
Must be using some other method then since there are spots where you can exclude what is in maintenance.  Is it only looking at what is actively in maintenance rather than setting a flag when a trigger fires and it was in maintenance?

**Comment by volter** [comment]
Yep, see https://support.zabbix.com/browse/ZBXNEXT-1150
