### ISSUE TITLE
Item name is being show with host name

### ISSUE THREAD

**Issue by evandro-portugal** [alexanderzobnin/grafana-zabbix#261]
Hi.
Whenever we use a template variable (and so a regex) for the host, items are show in the format "HOSTNAME.ITEMNAME". This is expected if we have multiple host selected in the template variable or multiple hosts retrieved by a regex.
The problem is, earlier versions would not act like this if just one host is selected/retrieved, and on the current version it comes like this everytime. I would suggest to retrieve only item name when a single host is selected, since retrieving hostname+itemname everytime gets a little messy.

**Comment by alexanderzobnin** [comment]
Yes, looks like a little bug. I'm going to add more features to `alias()` function, which allows you to override this behaviour. For example, show always only host or item name.

**Comment by evandro-portugal** [comment]
@alexanderzobnin Good to know! Do you have an estimate date for this fix or for a newer version? Thanks!

**Comment by Cbryndum** [comment]
I have this one too.

**Comment by Wicaeed** [comment]
Does anyone know if the opposite is true as well?

We have a dashboard of servers that displays data from a single server at a time. During a recent restart of our grafana container, it seems that the Zabbix Plugin was updated to 3.1.1, and now the host name is being included with the item name on all Zabbix items.

This is a problem for some of our users since the hostname being used can be very long, causing the legend visualization to be completely unusable since the name is too long.

Short of forcing the Zabbix plugin to a specific version that doesn't include this feature, is there any way to not use this option when only displaying data from a single host?

**Comment by Wicaeed** [comment]
+1

**Comment by grayhemp** [comment]
+1

**Comment by grayhemp** [comment]
There is a pool request #285 that suggest an alternative solution, basically returning the previous behavior back. TBH, I think it makes more sense to have that by default.

**Comment by Cbryndum** [comment]
I agree a rollback on this issue would be wise.

**Comment by Wicaeed** [comment]
Any chance we could get this fix merged into the grafana-zabbix-app repo as well so the grafana-cli can be used to install the fixed version?

**Comment by alexanderzobnin** [comment]
May be I'll fix some bugs and accumulate its into next patch version for grafana.net.

**Comment by darox** [comment]
What's the best way to remove the item name behind the host name?

**Comment by alexanderzobnin** [comment]
@darox I think you could use `replaceAlias()` function.

**Comment by darox** [comment]
@alexanderzobnin Can you indicate how exactly?

**Comment by alexanderzobnin** [comment]
Just read the docs.
