### ISSUE TITLE
No data points returned

### ISSUE THREAD

**Issue by andreipietrosu** [alexanderzobnin/grafana-zabbix#346]
Hello,

Versions: 
-zabbix: 3.0.6
-grafana: 4.1.1
-zabbix plugin version 3.2.1
-centos 7

I'm having some issues with gathering data from zabbix. The data source is connected successfully but when I configure a graph I get the following message: "no data points returned from metric query. I have set the MAX DATA POINTS TO 100 also without any progress. The group and host are identical to the ones I have defined in zabbix.

<img width="1432" alt="screen shot 2017-02-08 at 17 20 31" src="https://cloud.githubusercontent.com/assets/23555377/22743705/ac1eba1c-ee23-11e6-9cfe-994c2fb04caf.png">

**Comment by alexanderzobnin** [comment]
Try to check user's permissions.

**Comment by andreipietrosu** [comment]
Hello Alexander,

Not really sure what you mean. The users is administrator and administrator group permissions look like this:
<img width="1239" alt="screen shot 2017-02-09 at 10 40 01" src="https://cloud.githubusercontent.com/assets/23555377/22775381/3221a8dc-eeb4-11e6-8d0a-bb668af440b0.png">

**Comment by alexanderzobnin** [comment]
Can you check zabbix api response for history.get method using browser developer tools?

**Comment by Megaten-NZ** [comment]
I had same issue. Data Source okay but no datapoints etc. I tried Admin user in Grafana instead and it worked! I realised Admin is a special user account with Super Admin privileges. Create a new User Group, click permissions and add Host Groups with **Read** permissions. Add your API user to this group and try Grafan again. Worked for me.

**Comment by maxem** [comment]
got the same result with zabbix 3.4.1.

you just have to add the api user which you defined in the plugin settings (datasource settings) to a zabbix group which has read permissions to host groups.  Refresh and you see directly the charts working


@alexanderzobnin think this can be closed, even its rly old :)


![zabbix](https://user-images.githubusercontent.com/3196677/29875625-e3883eee-8d9a-11e7-8dee-5d46f14f3cc5.PNG)

**Comment by echel0n** [comment]
OK So I tried creating a new user with read only access and tried using Admin user both yielding the same result "no data points", I'm using Zabbix 3.4.1 with Grafana 4.4.3 and Zabbix plugin 3.6.1

Any ideas ?

**Comment by maxem** [comment]
I'm running following setup on one host: 

- Gafana v4.4.3, Zabbix Plugin v3.6.1, Zabbix v3.4.1

Installed the datasources:
- grafana-zabbix, ZabbixDB

API URL: 

- http://yourhost.domain/zabbix/api_jsonrpc.php

Configured Grafrana [http://docs.grafana-zabbix.org/installation/configuration/](url)

like mentioned above i don't got the shipped with dashboard working, so i added a api user with read only, but careful if u add new groups in zabbix you have to readd, for me it don't automatic add new groups. 


![grafa_3](https://user-images.githubusercontent.com/3196677/30435400-f95bc030-9969-11e7-8a85-829b13eafd06.PNG)
![grafana](https://user-images.githubusercontent.com/3196677/30435401-f985c5e2-9969-11e7-9631-130d66fb577e.PNG)
![grana_db](https://user-images.githubusercontent.com/3196677/30435402-f99be908-9969-11e7-99b6-6f9f1116e797.PNG)

**Comment by MikeGreyDog** [comment]
Hello
I'm having the same issue with the following configurations:
Centos 6
Zabbix 1.8 (I know that it's pretty old, but I have to use it)
Grafana 4.6.1
Zabbix plugin 3.7.0
So, my datasources configured:
![screenshot from 2017-11-09 11-01-03](https://user-images.githubusercontent.com/21245281/32600117-3430cb0c-c547-11e7-8a5c-5c455e259e1f.png)
![screenshot from 2017-11-09 11-00-31](https://user-images.githubusercontent.com/21245281/32600118-3459045a-c547-11e7-8946-72f1d44d75c6.png)
I've created the user with read permissions and api access on my Zabbix server:
![screenshot from 2017-11-09 11-01-47](https://user-images.githubusercontent.com/21245281/32600137-4af4c276-c547-11e7-8ed1-d97e71fba61a.png)
![screenshot from 2017-11-09 11-02-07](https://user-images.githubusercontent.com/21245281/32600141-4c9c92ca-c547-11e7-9144-8da8ce9d1eb8.png)
But still have the nodatapoints error
![screenshot from 2017-11-09 11-01-25](https://user-images.githubusercontent.com/21245281/32600178-6e620318-c547-11e7-94af-689b84deaa2d.png)
Also I can't check the Query inspector because it only showing the spinning wheel
![screenshot from 2017-11-09 11-10-44](https://user-images.githubusercontent.com/21245281/32600213-8c322b70-c547-11e7-85f8-53574d5ac763.png)

I would be very appreciate for any help.

**Comment by MikeGreyDog** [comment]
I found the next interesting information using the browser DevTools:
Requets:
{jsonrpc: "2.0", method: "host.get",…}
auth:"0542b6239996c701729138f8c3cb171f"
id:1
jsonrpc:"2.0"
method:"host.get"
params: {output: ["name", "host"], sortfield: "name", groupids: ["4"]}

Response:
{"jsonrpc":"2.0","result":[],"id":1}

Result is empty.
The reason is that the "output" parameter in Zabbix API 1.3 is not an array, and can't take the ["name", "host"] values. It is a string, which can take only " shorten, refer, extend" values.

**Comment by alexanderzobnin** [comment]
@MikeGreyDog not sure plugin works correctly with prior to 2.0 versions 😞

**Comment by alexanderzobnin** [comment]
I think this is similar to #352
