### ISSUE TITLE
Feature request::Query hosts satisfying multiple groups

### ISSUE THREAD

**Issue by deshike22** [alexanderzobnin/grafana-zabbix#512]
### I'm submitting a ...
- [ ] Feature requestdd

#### Description

Is there a way for me to query for hosts which is satisfying multiple groups instead of getting hosts of all groups. For eg:

Group1 contains host1,host2,host3
Group 2 contains host1,host4,host5

I want to query for hosts belonging to both Group1 and Group2 which is host1
I don't want to have my results as host1,host2,host3,host4,host5

This eliminates the use of zabbix nested host groups which is not really up to my expectation yet. Actually Zabbix should have implemented tags/labels for hosts instead of grouping. Large environments monitoring objects may related multiple environments, application, instances etc.

**Comment by alexanderzobnin** [comment]
Not sure I'm going to implement this. It's really a tags case, not host groups.

**Comment by HorselessName** [comment]
Hello. I see. So in your view you tend to believe that when querying a host that needs multiple conditions achieved, instead of doing something like querying a group named "Cloud Servers" and another one called "Windows Servers" we instead should use the "Item Type" tags, which I believe the field is called "Application"...

Yes? But what if we want to template stuff even further? Something like:

Let's say I monitor 10 clients, and all of them have multiple servers and services.
They have Linux Servers, Windows Servers, Local and Cloud Servers.

So I would a filter (Which is the case actually in my scenario) that I would do something like:

1. Select Client Group (Client A, B, C, etc.).
2. Select Service Type of the Client (Windows Server, Linux, APIs)
3. Select the Host (Cluster A, Cluster B, Server A, Server B, etc)

Is still the case to implement all this using tags and not host groups?
