### ISSUE TITLE
Per-datasource cache and auth storage

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#812]
Initial work is done, but as mentioned in https://github.com/alexanderzobnin/grafana-zabbix/pull/808#discussion_r331600052, we should store cache and auth for each particular data source, not for the package at all. So we need an object that stores information related to data source, like:
```golang
type ZabbixDatasource struct {
	plugin.NetRPCUnsupportedPlugin
	logger    hclog.Logger
	instances map[int64]ZabbixInstance
}

type ZabbixInstance struct {
	dsInfo *datasource.DatasourceInfo
	cache  *Cache
	auth   string
}
```
This is just an example, so maybe there's better solution.

**Comment by alecxvs** [comment]
I had some brief conversation with @dneth about this last week and trying to cache datasource info introduces some interesting problems. Knowing when datasources are updated so we can invalidate the cache is tricky. At least from the UI, if we always Save & Test, we can rely on the front end to send some kind of test request and invalidate the cache/instance when that happens. But I don't know if we can guarantee that always is the case.

I think ideally Grafana would give us more state, because the way the rpc plugins are arranged, it almost forces the plugins to be stateless. But that's a lot harder to change.

**Comment by alexanderzobnin** [comment]
Good catch! Yes, this is tricky right now. I think we can start with "Save and Test" approach: build special `test` query type which will handle test requests from the frontend and invalidate cache.

**Comment by alecxvs** [comment]
I was going to create an issue for creating a Test query type, but after thinking about it, I'm not sure we need it. Though I'm entirely speculating since I don't know the frontend code very well...

The frontend currently submits some query to test the connection. We only need to change that to run the same query on the backend. As for expiring the auth token... We probably don't need to explicitly expire it. The cache should expire after a period of time. If the login information changes, as part of the per-datasource caching, perhaps we can hash the credentials and use that to access the cache.

**Comment by alecxvs** [comment]
I'm working on this

**Comment by alecxvs** [comment]
I looked at the connection test and it doesn't simply execute a query, so I was mistaken there. Anyways, connection test implementation is included with the changes in my PR ^
