### ISSUE TITLE
Add Operational data to Problems

### ISSUE THREAD

**Issue by liyuanchuan8** [alexanderzobnin/grafana-zabbix#828]
hello，
in zabbix4.4 add new future ,display Operational data like this:

![image](https://user-images.githubusercontent.com/18182080/68013764-ba412100-fcc8-11e9-9619-8bc488694a57.png)
@alexanderzobnin could you add this in trigger display in new version，thanks。

**Comment by alexanderzobnin** [comment]
Could you point me to the Zabbix docs? What does _Operational data_ mean?

**Comment by i-ky** [comment]
You can start with [What's new in 4.4.0](https://www.zabbix.com/documentation/current/manual/introduction/whatsnew440#liveoperational_data_of_problems). Basically, it is a field where users are now supposed to use {ITEM.LASTVALUE<1-9>} macros, since _Problem name_ [became static in 4.0.0](https://www.zabbix.com/documentation/4.0/manual/installation/upgrade_notes_400#problem_name_generation).

**Comment by matiasba** [comment]
> Could you point me to the Zabbix docs? What does _Operational data_ mean?

Operational data is basically what {ITEM.LASTVALUE1} used to be, since 4.0 Problems became static because the devs think that people search problems by the exact problem name that they receive by mail. Based on that they decided to add a dynamic parameter to the trigger configuration called _Operational data_ which show the latest data available for a variety of macros included the previously used {ITEM.LASTVALUE1}.
What we need is a way to display the _Operational data_  next to the trigger name for a quick glance a the real severity of the problem.

[Here](https://www.zabbix.com/documentation/current/manual/config/triggers/trigger) you can read about the _Operational data_ parameter
And [here](https://support.zabbix.com/browse/ZBXNEXT-4942) you can read the full discussion about in the zabbix issue tracker

Looking at the amount of votes and followers on the issue it I'm guessing that a lot of people are interesting in this. I would gladly buy you a beer for this one :)

**Comment by ISnotes** [comment]
Добрый день! Я так понимаю предложение дальше предложения не продвинулось)
А функционал очень важный. Ни одна панель в заббиксе без него не обходится.
Что показывают эти оперативные данные? Вот, например, на скриншоте ниже видно, что у меня есть проблемы с дисками. В панели заббикса оперативные данные мне показывают, что у атрибута 199 показатель 62, а у атрибута 197 - 7 секторов. Очень наглядно, хотелось бы видеть в графане прямо на панели.
![image](https://user-images.githubusercontent.com/12543500/162467374-0fe60487-268a-43b4-979a-d39aec5d43a3.png)
![image](https://user-images.githubusercontent.com/12543500/162468246-7999507d-5392-429d-928a-94426dbb314a.png)

**Comment by Justify87** [comment]
Any news on this? It's really annoying to have old values in the title of the problem

**Comment by alexanderzobnin** [comment]
Sorry, this duplicates #1260. Issue is fixed and will be available in next release.
