### ISSUE TITLE
Support TimescaleDB?

### ISSUE THREAD

**Issue by AguirreIF** [alexanderzobnin/grafana-zabbix#914]
Hi, I have Zabbix with PostgreSQL + TimescaleDB. [Grafana v5.3 added a new graphical query editor for PostgreSQL with TimescaleDB compatibility](https://blog.timescale.com/blog/grafana-time-series-exploration-visualization-postgresql-8c7baa9c3bfe/). 

Does the query editor in Metrics mode support TimescaleDB?

![Query editor in Metrics mode](https://alexanderzobnin.github.io/grafana-zabbix/img/getstarting-metrics_filtering.png)

Regards,

**Comment by i-ky** [comment]
As far as I know, TimescaleDB is fully compatible with PostgreSQL syntax on SQL query level and in Zabbix plugin you don't even touch SQL, because all configuration data is pulled from Zabbix API which provides abstraction layer on top of SQL. What TimescaleDB-specific features do you expect to see in Zabbix plugin's query editor?

**Comment by AguirreIF** [comment]
> As far as I know, TimescaleDB is fully compatible with PostgreSQL syntax on SQL query level and in Zabbix plugin you don't even touch SQL, because all configuration data is pulled from Zabbix API which provides abstraction layer on top of SQL. What TimescaleDB-specific features do you expect to see in Zabbix plugin's query editor?

Yes, you're right, the Zabbix API takes care of that.
