### ISSUE TITLE
Triggers: acknowledged filter doesn't work

### ISSUE THREAD

**Issue by tolstiyman** [alexanderzobnin/grafana-zabbix#985]
**Describe the bug**
In the query editor (Triggers mode), Acknowledged filter doesn't change anything(I know that 20 from 23 problems are acknowleged).

**Expected behavior**
Only acknowledged or unacknowledged triggers.

**Screenshots**
![all](https://user-images.githubusercontent.com/16821389/84249888-03d1d400-ab14-11ea-8066-b776a69ddcc7.png)
![unack](https://user-images.githubusercontent.com/16821389/84249892-05030100-ab14-11ea-9291-20820f1250b4.png)
![ack](https://user-images.githubusercontent.com/16821389/84249894-059b9780-ab14-11ea-8ade-395128c8e028.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.1   | 5.0.0  | 3.12.2                 |

**Comment by heyrod** [comment]
My guess is that it incorrectly queries Zabbix. For unacknowledged alerts, the query should include "Acknowledged=0", for acknowledged -- "Acknowledged=1", and for all triggers - nothing.

**Comment by zbxsyr** [comment]
The v3.12.2 query editor (Triggers mode) does not save the proper parameter value to the dashboard.
![image](https://user-images.githubusercontent.com/55248938/85576048-59d86880-b638-11ea-9ce3-c49ffbcda0c7.png)

If I manually fix the dashboard JSON model, it will show the real all triggers / acknowledged / unacknowledged values.

Dashboard JSON model:
 - **wrong**: the value is always 2 within the actual panel block -> "targets" -> "triggers" -> "acknowledged" section
![image](https://user-images.githubusercontent.com/55248938/85575511-e59dc500-b637-11ea-8082-25c91637e0a4.png)
 - **wrong**: it is updating only the panel -> "targets" -> "options" -> "acknowledged" section, but it is also not saved properly in every case and it is not relevant in my case.

This was working with the editor in v3.11.0 (but that version has other mission critical bugs in our use cases).
Until (at least) this is not fixed, we do not have a fully working plugin for Grafana v6 and v7.

**Software versions**
Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
6.7.4 | 4.0.21 | 3.12.2
7.0.3 | 4.0.21 | 3.12.2

**Comment by alexanderzobnin** [comment]
HI! Can you check this issue in latest plugin version?

**Comment by zbxsyr** [comment]
Hello @alexanderzobnin!

There is no difference.

---

**Software versions**
Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.0.3 | 4.0.21 | 4.0.1
7.1.5 | 4.0.21 | 4.0.1

**Comment by Positronico** [comment]
Issue seems to be present also on Problems query. The Unacknowledged filter behaves just like no filter (shows unacknowledged and acknowledged). It's possible to filter for Acknowledged only, though.

![Screen Shot 2020-11-11 at 4 38 30 PM](https://user-images.githubusercontent.com/23188958/98880948-bd273380-243d-11eb-9755-e0f9253bdbe2.png)


Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.0.3 | 4.0.21 | 4.0.1
7.1.5 | 4.0.21 | 4.0.1
7.3.1 | 4.4.10 | 4.0.1

**Comment by alexanderzobnin** [comment]
Yes, confirmed: this bug still present. 
I've found a workaround that makes me to think about deprecating `Triggers` editor mode. With new `Transform` feature it's possible to use `Problems` mode instead of `Triggers` to count problems, just use `Series to rows` with `count` transformation:

![Screenshot from 2020-11-12 13-05-13](https://user-images.githubusercontent.com/4932851/98926043-da184100-24e7-11eb-911e-3b6862550fe0.png)

![Screenshot from 2020-11-12 13-05-27](https://user-images.githubusercontent.com/4932851/98926057-dd133180-24e7-11eb-8954-be4ac0e1d3dc.png)

In this mode filters work as expected.

**Comment by Positronico** [comment]
Something I noticed recently: I was considering the filled chat bubble as an acknowledged problem and the clear one as unacknowledged. Turns out the filled/unfilled only tells you the problem has COMMENTS in it, not necessarily the "Acknowledge" checkbox was checked.

This assumptions came from the fact in previous version there were not such checkbox. A comment was an acknowledge. But today we have the option to just add a comment without acknowledging it and even change problem severity.

Maybe there is room for UI improvement here (with different icons for ack/comments and ack checkbox defaults to checked) but I can confirm the filter is working properly for ack'ed/unack'ed problems.

**Comment by GauthierSgds** [comment]
Hi,

For Grafana 8.3.7 and plugin 4.2.5 I haved the same issue. After looking in the code, 

I edited line 351 in query.editor.html
ng-model="ctrl.target.options.acknowledged" --> ng-model="ctrl.target.triggers.acknowledged"

And added line acknowledged?: '1' | '0'; in interface ZBXProblem in type.ts file

After rebuild plugin, filter works again.

Regards

**Comment by GauthierSgds** [comment]
Hi @alexanderzobnin, can you put into next release correction on query.editor.html file --> replace ng-model="ctrl.target.options.acknowledged"  by ng-model="ctrl.target.triggers.acknowledged" and add line acknowledged?: '1' | '0'; in interface ZBXTrigger in type.ts file?

Thanks in advance!

**Comment by dayatto** [comment]
any help or suggest for this case ?
i'm still can't to display number of counting problem each severity using filter acknowledge or unacknowledge.
use the stats panel or table same issue.
hope any help this case
thankyou

**Comment by alexanderzobnin** [comment]
I think I fixed it during the refactoring, so let's check how it works after release.
